- name: Rollback
  hosts: localhost
  gather_facts: no
  roles:
    - role: rollback
      vars:
        clean_migration_timeout: 120
        change_migration_timeout: 120
        network_type: OpenShiftSDN
        mco_update_timeout: 300s
        mcp_completion_timeout: 18000  # Timeout in seconds
        sdn_co_timeout: 120  # Timeout in seconds
        sdn_multus_timeout: 300  # Timeout in seconds for waiting for Multus pods
        verify_machine_config_timeout: 300
        disable_auto_migration: true # Enables disable_automatic_migration
        egress_ip: false
        egress_firewall: false
        multicast: false
        configure_network_type: openshiftSDN
        #mtu: 1400
        #vxlanPort: 4790


